version: '3.1'

services:

  db:
    container_name: db
    image: postgres:11.1-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: greeting
      POSTGRES_USER: greeting
    ports:
      - 5432:5432
    volumes:
      - ./greeting.sql:/docker-entrypoint-greeting.d/greeting.sql